# Generated by Django 2.2.4 on 2019-09-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplacesForReddit', '0003_auto_20190903_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='selftext',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='selftext_html',
            field=models.TextField(null=True),
        ),
    ]
