# Generated by Django 2.2.5 on 2019-10-01 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplacesForReddit', '0004_auto_20190903_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedListing',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MarketplacesForReddit.Listing')),
                ('location', models.CharField(max_length=10)),
                ('has', models.CharField(max_length=300)),
                ('wants', models.CharField(max_length=300)),
            ],
        ),
    ]
