# Generated by Django 2.2.4 on 2019-09-02 19:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('author_flair_richtext', django.contrib.postgres.fields.jsonb.JSONField()),
                ('author_flair_text', models.CharField(max_length=50)),
                ('author_flair_type', models.CharField(max_length=50)),
                ('author_fullname', models.CharField(max_length=16)),
                ('created_utc', models.DateTimeField()),
                ('domain', models.CharField(max_length=25)),
                ('edited', models.DateTimeField()),
                ('link_flair_css_class', models.CharField(max_length=50)),
                ('link_flair_richtext', django.contrib.postgres.fields.jsonb.JSONField()),
                ('link_flair_text', models.CharField(max_length=50)),
                ('link_flair_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('permalink', models.CharField(max_length=300)),
                ('selftext', models.TextField()),
                ('selftext_html', models.TextField()),
                ('subreddit', models.CharField(max_length=20)),
                ('subreddit_id', models.CharField(max_length=8)),
                ('subreddit_name_prefixed', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
