# Generated by Django 2.2.4 on 2019-09-04 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplacesForReddit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='author_flair_richtext',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='author_flair_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='link_flair_richtext',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='link_flair_type',
        ),
    ]
