# Generated by Django 2.2.5 on 2019-10-01 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplacesForReddit', '0005_parsedlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedlisting',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MarketplacesForReddit.Listing'),
        ),
    ]
