# Generated by Django 2.2.5 on 2019-11-13 19:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('MarketplacesForReddit', '0006_auto_20191001_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_text', models.CharField(max_length=300)),
                ('search_title_only', models.BooleanField()),
                ('location', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('date_within', models.IntegerField()),
                ('trade_amount', models.IntegerField()),
                ('trade_sort', models.CharField(max_length=10)),
                ('listing_type', models.CharField(max_length=300)),
                ('payment_type', models.CharField(max_length=300)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=500)),
                ('query_string', models.CharField(max_length=500)),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session')),
            ],
        ),
    ]
