# Generated by Django 2.2.5 on 2019-11-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplacesForReddit', '0007_searchlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='session_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
