# Generated by Django 2.2.5 on 2019-11-13 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplacesForReddit', '0009_auto_20191113_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchlog',
            old_name='date',
            new_name='query_date',
        ),
        migrations.RenameField(
            model_name='searchlog',
            old_name='date_within',
            new_name='query_date_within',
        ),
        migrations.RenameField(
            model_name='searchlog',
            old_name='listing_type',
            new_name='query_listing_type',
        ),
        migrations.RenameField(
            model_name='searchlog',
            old_name='location',
            new_name='query_location',
        ),
        migrations.RenameField(
            model_name='searchlog',
            old_name='payment_type',
            new_name='query_payment_type',
        ),
        migrations.RenameField(
            model_name='searchlog',
            old_name='search_text',
            new_name='query_search_text',
        ),
        migrations.RenameField(
            model_name='searchlog',
            old_name='search_title_only',
            new_name='query_search_title_only',
        ),
        migrations.RenameField(
            model_name='searchlog',
            old_name='trade_amount',
            new_name='query_trade_amount',
        ),
        migrations.RenameField(
            model_name='searchlog',
            old_name='trade_sort',
            new_name='query_trade_sort',
        ),
        migrations.AddField(
            model_name='searchlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
